extends CharacterBody2D
class_name Player

##
## Represents the controllable character in the game.
## Detailed Description: The Player node handles all core gameplay mechanics such as movement, 
## gravity inversion, mode switching, collision detection, and interactions with game modifiers. 
## It manages multiple gameplay modes (Square, Wave, UFO, Ball, Robot, Spaceship), 
## each with its own physics and behavior, and emits signals to communicate player state to other systems.

@onready var hurt_box: Area2D = %HurtBox
@onready var spawn: Marker2D = %PlayerSpawn ## Node that contains the player's spawn position
@onready var player_elements: Node2D = %PlayerElements ## Node that contains visual elements generated by the player
@onready var wave_lines: Node2D = %WaveLines ## Node that stores the [WaveTrial] generate by [WaveMode]

@onready var square_mode: SquareMode = $SquareMode
@onready var wave_mode: WaveMode = $WaveMode
@onready var ufo_mode: ModeBase = $UfoMode
@onready var ball_mode: BallMode = $BallMode
@onready var robot_mode: RobotMode = $RobotMode
@onready var spaceship_mode: SpaceshipMode = $SpaceshipMode

# Enums
## Variable that controls the active gravity direction of the player
@export var _gravity_dir: Enums.GRAVITY_DIR = Enums.GRAVITY_DIR.NORMAL

## Stores the player's initial mode
@export var _initial_mode: Enums.PLAYER_MODE

## Indicates the gravity strength
var _gravity_force_multiplier: Enums.GRAVITY_FORCE = Enums.GRAVITY_FORCE.NORMAL

## Represents the direction the player is moving
var _player_direction: Enums.PLAYER_DIRECTION = Enums.PLAYER_DIRECTION.RIGHT

# Resources
## Structure made to store the resources of all modes [br]
## All resources derive from [PlayerBaseResource]
var _player_resources: Dictionary[Enums.PLAYER_MODE, PlayerBaseResource]
var _square_rsc: SquareResource = SquareResource.new()
var _wave_rsc: WaveResource = WaveResource.new()
var _ufo_rsc: UfoResource = UfoResource.new()
var _ball_rsc: BallResource = BallResource.new()
var _spaceship_rsc: SpaceshipResource = SpaceshipResource.new()
var _robot_rsc: RobotResource = RobotResource.new()
var _active_rsc: PlayerBaseResource

# Modifiers
var _is_on_orb: bool = false
var _is_on_pad: bool = false
var _modifier_used: bool = false

## Stores the effect of the [PlayerModifier] that the player is currently in
## This effect can be [enum JUMPS] or [enum GRAVITY]
var _modifier_effect: Variant # Can be ENUM.(JUMP/GRAVITY)

# Position Verifier
var _old_x_position: int
var _position_verified: bool = false

# Mode
## Contains the [code]enum[/code] that represents the player's current mode
var _mode: Enums.PLAYER_MODE
var _active_mode: ModeBase

# Action
var _can_action: bool = true ## Checks if the player can perform an action
var _action_pressed: bool
var _action_clicked: bool
var _action_released: bool

var _wave_trial: WaveTrial
const _WAVE_TRIAL_SCENE_PATH: String = "res://Player/Modes/WaveMode/Scenes/wave_trial.tscn"
const _WAVE_TRIAL_SCENE: PackedScene = preload(_WAVE_TRIAL_SCENE_PATH)

#region Ready Func
func _ready() -> void:
	_connect_signals()
	_setup_player_resources()
	change_mode(_initial_mode)
#endregion

func _physics_process(delta: float) -> void:
	_emit_player_regular_signals()
	_refresh_input_states()
	_reset_gravity_force_if_on_surface()
	_is_inside_player_modifier()
	_is_player_in_action()
	_kill_on_idle()

	match _mode:
		Enums.PLAYER_MODE.SQUARE: _square_mode(delta)
		Enums.PLAYER_MODE.WAVE: _wave_mode(delta)
		Enums.PLAYER_MODE.BALL: _ball_mode(delta)
		Enums.PLAYER_MODE.UFO: _ufo_mode(delta)
		Enums.PLAYER_MODE.SPACESHIP: _spaceship_mode(delta)
		Enums.PLAYER_MODE.ROBOT: _robot_mode(delta)

	velocity.x = _active_rsc.speed * _player_direction
	move_and_slide()

#region Actions

## Updates the player's input state each frame
func _refresh_input_states() -> void:
	_action_pressed = Input.is_action_pressed("Action")
	_action_clicked = Input.is_action_just_pressed("Action")
	_action_released = Input.is_action_just_released("Action")

## Checks if the player is performing an action or is inside an
## [Orb] or [Pad]
func _is_player_in_action() -> void:
	if _action_clicked or _action_pressed or _orb_jump() or _pad_jump():
		Events.emit_signal("player_is_in_action", true)
	else:
		Events.emit_signal("player_is_in_action", false)
#endregion

func _set_spawn_position() -> void:
	global_position = spawn.global_position

#region Signals
func _emit_player_regular_signals() -> void:
	Events.emit_signal("player_pos", global_position)
	Events.emit_signal("player_in_floor", is_on_floor())
	Events.emit_signal("player_in_ceiling", is_on_ceiling())

func _connect_signals() -> void:
	robot_mode.connect("robot_fly_timeout", _on_robot_fly_timeout)
#endregion

#region ModifiersActions

## Checks if the player can use [PlayerModifier] [br]
## if true, executes [method _identify_effect]
func _is_inside_player_modifier() -> void:
	if _can_use_modifier():
		_identify_effect()
		_modifier_used = true
		if _orb_jump():
			Events.emit_signal("player_use_orb")

## Executes functions that check which effects are inside [member _modifier_effect]
func _identify_effect() -> void:
	_is_jump_effect()
	_is_gravity_effect()
	_is_gravity_force_effect()

## Checks if the [member _modifier effect] has the modifier [enum MODIFIERS.JUMP]
func _is_jump_effect() -> void:
	var _effect: Variant = _modifier_effect.get(Enums.MODIFIERS.JUMP)
	if _effect != null: _jump_modifiers_actions(_effect)

## Checks if the [member _modifier_effect] has the modifier [enum MODIFIERS.GRAVITY]
func _is_gravity_effect() -> void:
	var _effect: Variant = _modifier_effect.get(Enums.MODIFIERS.GRAVITY)
	if _effect != null: _gravity_modifiers_actions(_effect)

## Checks if the player meets the conditions to use a [PlayerModifier]
func _is_gravity_force_effect() -> void:
	var _effect: Variant = _modifier_effect.get(Enums.MODIFIERS.G_FORCE)
	if _effect != null: _gravity_force_modifiers_actions(_effect)

## Checks if the jogador está dentro das condições para utilizar um [PlayerModifier]
func _can_use_modifier() -> bool:
	return (_orb_jump() or _pad_jump()) and not _modifier_used

#region DirectionSetter
func set_direction(new_dir: Enums.PLAYER_DIRECTION = Enums.PLAYER_DIRECTION.RIGHT) -> void:
	_player_direction = new_dir
	_update_scale_x_by_direction()
#endregion
#endregion

#region Resources

## Changes the player's [member _active_rsc] based on [member _mode]
## This function is executed in [method _on_mode_entered]
func _set_active_resource() -> void:
	_active_rsc = _player_resources.get(_mode)

## Assigns the resource of each player mode [br]
## Each key is an element of [enum PLAYER_MODE]
func _setup_player_resources() -> void:
	_player_resources = {
		Enums.PLAYER_MODE.SQUARE: _square_rsc,
		Enums.PLAYER_MODE.WAVE: _wave_rsc,
		Enums.PLAYER_MODE.UFO: _ufo_rsc,
		Enums.PLAYER_MODE.BALL: _ball_rsc,
		Enums.PLAYER_MODE.SPACESHIP: _spaceship_rsc,
		Enums.PLAYER_MODE.ROBOT: _robot_rsc
	}
#endregion

#region JumpActions

## Executes the function [method _jump] passing [param effect]
func _jump_modifiers_actions(effect: Enums.JUMPS) -> void:
	_jump(effect)

func _orb_jump() -> bool:
	return _action_clicked and _is_on_orb

func _pad_jump() -> bool:
	return _is_on_pad

## Performs the jump according to the value passed in [param jump_size]
func _jump(jump_size: Enums.JUMPS = Enums.JUMPS.MEDIUM) -> void:
	match jump_size:
		Enums.JUMPS.SMALL: velocity.y = (_active_rsc.jump_height * _gravity_dir) / 1.8
		Enums.JUMPS.MEDIUM: velocity.y = _active_rsc.jump_height * _gravity_dir
		Enums.JUMPS.MEDIUM_HIGH: velocity.y = _active_rsc.jump_height * _gravity_dir * 1.5
		Enums.JUMPS.HIGH: velocity.y = _active_rsc.jump_height * _gravity_dir * 3
#endregion

#region ModeControl

## Changes the player's mode
## [br] - param: [param Enums.PLAYER_MODE] [br]
## [member Orbs] trigger this function when the player enters
func change_mode(new_mode: Enums.PLAYER_MODE) -> void:
	_mode = new_mode
	_on_mode_entered()

## Executes all necessary functions when switching [member _mode]
func _on_mode_entered() -> void:
	_disconnect_modes_events()
	_reset_modes_visibility()
	_set_active_resource()
	_reset_transform()
	_set_active_mode()
	_set_mode_visual(_active_mode, true)
	_set_mode_collision(_active_mode)

## Checks the value of [member _mode] and determines the [member _active_mode] based on the result
## Also executes [color=light_blue]_on_enter_(mode_name)[/color] to run functions
## required when entering a mode
func _set_active_mode() -> void:
	match _mode:
		Enums.PLAYER_MODE.SQUARE: 
			_active_mode = square_mode
			_on_enter_square_mode()
		Enums.PLAYER_MODE.WAVE:
			_active_mode = wave_mode
			_on_enter_wave_mode()
		Enums.PLAYER_MODE.BALL:
			_active_mode = ball_mode
			_on_enter_ball_mode()
		Enums.PLAYER_MODE.UFO:
			_active_mode = ufo_mode
			_on_enter_ufo_mode()
		Enums.PLAYER_MODE.ROBOT:
			_active_mode = robot_mode
			_on_enter_robot_mode()
		Enums.PLAYER_MODE.SPACESHIP: 
			_active_mode = spaceship_mode
			_on_enter_spaceship_mode()

## Sets the value of [member ModeBase.visible] through the parameter [param be_visible]
func _set_mode_visual(node: ModeBase, be_visible: bool) -> void:
	node.visible = be_visible

## Retrieves the [ModeBase] nodes and applies the value [code]false[/code] to the attribute [member ModeBase.visible]
func _reset_modes_visibility() -> void:
	for item: Node2D in get_children():
		if item is ModeBase:
			_set_mode_visual(item, false)

## Emits the signal so that [PlayerCollision] [br]
## obtains [member CollisionShape2D.shape] do [param mode] and applies to [member PlayerCollision.shape]
func _set_mode_collision(mode: ModeBase) -> void:
	Events.emit_signal("set_player_collision_shape", mode.get_collision_shape())

func _disconnect_modes_events() -> void:
	pass
#endregion

#region Gravity
func _apply_gravity(delta: float) -> void:
	velocity.y += _active_rsc.gravity * _gravity_dir * delta * _gravity_force_multiplier

func _invert_gravity() -> void:
	if _gravity_dir == Enums.GRAVITY_DIR.NORMAL:
		_gravity_dir = Enums.GRAVITY_DIR.INVERTED
	else:
		_gravity_dir = Enums.GRAVITY_DIR.NORMAL
	_update_scale_y_by_gravity()

func _set_gravity_dir(new_dir: Enums.GRAVITY_DIR) -> void:
	_gravity_dir = new_dir
	_update_scale_y_by_gravity()

func _reset_gravity_force_if_on_surface() -> void:
	if is_on_floor() or is_on_ceiling(): _set_gravity_force()
	
func _set_gravity_force(force: Enums.GRAVITY_FORCE = Enums.GRAVITY_FORCE.NORMAL) -> void:
	_gravity_force_multiplier = force

func _gravity_modifiers_actions(effect: Enums.GRAVITY_DIR) -> void:
	match effect:
		Enums.GRAVITY_DIR.FLIP: _invert_gravity()
		Enums.GRAVITY_DIR.INVERTED: _set_gravity_dir(Enums.GRAVITY_DIR.INVERTED)
		Enums.GRAVITY_DIR.NORMAL: _set_gravity_dir(Enums.GRAVITY_DIR.NORMAL)

func _gravity_force_modifiers_actions(effect: Enums.GRAVITY_FORCE) -> void:
	match effect:
		Enums.GRAVITY_FORCE.NORMAL: _set_gravity_force()
		Enums.GRAVITY_FORCE.STRONG: _set_gravity_force(Enums.GRAVITY_FORCE.STRONG)
#endregion

#region GameplayModes

#region Square

func _on_enter_square_mode() -> void:
	pass

func _square_mode(delta: float) -> void:
	if not is_on_floor() or not is_on_ceiling():
		_apply_gravity(delta)

	if _can_square_jump():
		_jump()

func _can_square_jump() -> bool:
	return _action_pressed and is_on_floor() or \
	_action_pressed and is_on_ceiling()
#endregion

#region Wave
func _on_enter_wave_mode() -> void:
	_instanciate_wave_trial()

func _wave_mode(_delta: float) -> void:
	velocity.y = _active_rsc.vertical_speed * _active_rsc.direction * _gravity_dir
	if _action_pressed:
		_change_wave_direction(Enums.WAVE_DIR.UP)
		_add_trial_point()
	else:
		_change_wave_direction(Enums.WAVE_DIR.DOWN)
		_add_trial_point()

## Emits the signal so that [PlayerCollision]
## obtains [member CollisionShape2D.shape] from [param mode] and applies it to [member PlayerCollision.shape]
func _instanciate_wave_trial() -> void:
	_wave_trial = _WAVE_TRIAL_SCENE.instantiate()
	_wave_trial.global_position = Vector2.ZERO
	wave_lines.add_child(_wave_trial)
	_add_trial_point()

## Executes [method WaveTrial.add_point] and inserts it at the position relative to [member global_position]
func _add_trial_point() -> void:
	if not _wave_trial: return
	var _local_pos = _wave_trial.to_local(global_position)
	_wave_trial.add_point(_local_pos)

func _change_wave_direction(new_dir: Enums.WAVE_DIR) -> void:
	_active_rsc.direction = new_dir
	_apply_wave_rotation_by_state()

## Rotates the player according to the state of [WaveMode]
func _apply_wave_rotation_by_state() -> void:
	if is_on_floor() or is_on_ceiling(): rotation_degrees = _active_rsc.IN_SURFACE_ROTATE_DEG * _gravity_dir
	elif _action_pressed: rotation_degrees = _active_rsc.ACTION_ROTATE_DEG * _gravity_dir
	else: rotation_degrees = _active_rsc.NOT_ACTION_ROTATE_DEG * _gravity_dir

#endregion

#region Ball

func _on_enter_ball_mode() -> void:
	pass

func _ball_mode(delta: float) -> void:
	_apply_gravity(delta)
	if _action_clicked and is_on_ceiling() : _invert_gravity()
	elif _action_clicked and is_on_floor(): _invert_gravity()
#endregion

#region Ufo

func _on_enter_ufo_mode() -> void:
	pass

func _ufo_mode(delta: float) -> void:
	_apply_gravity(delta)
	if _action_clicked:
		velocity.y = _active_rsc.impulse_height * _gravity_dir
#endregion

#region Spaceship

func _on_enter_spaceship_mode() -> void:
	pass

func _spaceship_mode(delta: float) -> void:
	if _action_pressed and _can_action:
		velocity.y += _active_rsc.vertical_vel * _gravity_dir
	else:
		_apply_gravity(delta)
#endregion

#region Robot
func _on_enter_robot_mode() -> void:
	pass

## The [RobotMode] can start flying when it is on a surface
## Once flight starts it can only fly again after touching a safe surface
## The property that defines if it can fly is [member RobotResource.can_fly]
func _robot_mode(delta: float) -> void:
	if (is_on_floor() and _gravity_dir == Enums.GRAVITY_DIR.NORMAL) \
	or (is_on_ceiling() and _gravity_dir == Enums.GRAVITY_DIR.INVERTED):
		_active_rsc.can_fly = true
	if not is_on_floor() and _action_released:
		_active_rsc.can_fly = false

	if _action_pressed and _active_rsc.can_fly:
		velocity.y = _active_rsc.boost_force * _gravity_dir
		robot_mode.start_fly_timer()
	else:
		_apply_gravity(delta)

func _on_robot_fly_timeout() -> void:
	_active_rsc.can_fly = false

#endregion
#endregion

#region Transform
## Inverts the y-axis of the root node of [Player] according to the gravity in which it is found
func _update_scale_y_by_gravity() -> void:
	scale.y = Enums.SCALE_DIR.NORMAL \
	if _gravity_dir == Enums.GRAVITY_DIR.NORMAL \
	else Enums.SCALE_DIR.INVERTED

## Inverts the x-axis of [Player] according to the direction he is heading
func _update_scale_x_by_direction() -> void:
	scale.x = Enums.PLAYER_DIRECTION.LEFT \
	if _player_direction == Enums.PLAYER_DIRECTION.LEFT \
	else Enums.PLAYER_DIRECTION.RIGHT
#endregion

#region Reset

## Resets gameplay-altered values to their default [br]
## This function is only triggered when the player dies
func _reset_player() -> void:
	# Transforms
	global_position = spawn.global_position
	_reset_transform()

	# Gravity
	_gravity_dir = Enums.GRAVITY_DIR.NORMAL
	
	# Velocity
	velocity = Vector2.ZERO

	# Modes
	change_mode(_initial_mode)
	_reset_robot_fly_mode()
	_erase_wave_lines()

func _reset_transform() -> void:
	rotation_degrees = 0
	_update_scale_y_by_gravity()
	_update_scale_x_by_direction()

func _reset_robot_fly_mode() -> void:
	robot_mode.reset_fly_timer()

func _erase_wave_lines() -> void:
	if wave_lines.get_children():
		for lines in wave_lines.get_children():
			lines.queue_free()
#endregion

#region DieFunctions

## Checks if the value of [member global_position.x] of the current frame is equal to that of the previous frame [br]
## If so, it means the player is idle or colliding with something.
## When this happens the function [method _died] is triggered
func _kill_on_idle() -> void:
	if not _position_verified:
		_old_x_position = int(position.x)
		_position_verified = true
	else:
		if int(position.x) == _old_x_position:
			_died()
		else:
			_old_x_position = 0
		_position_verified = false

func _died() -> void:
	Events.emit_signal("player_died")
	_reset_player()
#endregion

#region Interations
func _on_hurt_box_body_entered(_body: Node2D) -> void:
	_died()

## Obtains the type of [PlayerModifier] and its effect
func _on_modifier_sensor_area_entered(area: Area2D) -> void:
	if not area is PlayerModifier: return
	_identify_area_type(area)
	_get_modifier_effect(area)
	_can_action = false

func _get_modifier_effect(entered_area: Area2D) -> void:
	_modifier_effect = entered_area.get_effect()

func _identify_area_type(entered_area: Area2D) -> void:
	if entered_area is Orb: _is_on_orb = true
	elif entered_area is Pad: _is_on_pad = true

func _on_modifier_sensor_area_exited(area: Area2D) -> void:
	if not area is PlayerModifier: return
	_reset_modifier_variables()

# Reset the control variables of a [Player Modifier] after the player exits it
func _reset_modifier_variables() -> void:
	_is_on_orb = false
	_is_on_pad = false
	_can_action = true
	_modifier_used = false
#endregion
